name = "demo-2022-11-13"
main = "./src/index.mjs"
compatibility_date = "2022-09-08"

[durable_objects]
bindings = [{name = "DURABLISH", class_name = "DurableishCounter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableishCounter"]